In [1]:
import numpy as np
import math
import copy
import plotly.offline
import plotly.graph_objs as go

from simulpy.robobj import robot
from simulpy import view
from simulpy import fwdkin
from simulpy import trajectory

pi = math.pi

In [2]:
jointno = 3
jointaxismat = [[0,0,1],[0,1,0],[0,1,0]]
lenmat = [[0,0,1],[0,0,2],[0,0,3]]

robot1 = robot.Robot(jointno,jointaxismat,lenmat)

print(robot1.jointaxismat)

[[0, 0, 1], [0, 1, 0], [0, 1, 0]]


In [3]:
view.plotrobot(robot1)

[[0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 3.]
 [0. 0. 6.]]


In [4]:
thetafinal = [pi/3,pi/3,pi/3]
fwdkin.calc(robot1,thetafinal)

In [5]:
view.plotrobot(robot1)

[[ 0.          0.          0.        ]
 [ 0.          0.          1.        ]
 [ 1.29903811  2.25        1.5       ]
 [ 2.59807621  4.5        -3.        ]]


In [6]:
print(robot1.cureffpos)

[0. 0. 6.]


In [7]:
thetainit = [pi/5,pi/3,pi/4]
thetafinal = [pi/3,pi/6,pi/3]
nopoints = 10

trajectorymat = trajectory.calcont(robot1,thetainit,thetafinal,nopoints)
trajectory.plotcont(robot1,trajectorymat,nopoints,1)

In [8]:
thetainit = [pi/5,pi/3,pi/4]
thetafinal = [pi/3,pi/6,pi/3]
nopoints = 10

trajectorymat = trajectory.calcdisc(robot1,thetainit,thetafinal,nopoints)
trajectory.plotdisc(robot1,trajectorymat,nopoints,1)

print(trajectorymat[33])

nopoints = copy.deepcopy(nopoints*robot1.jointno + robot1.jointno - 1)
x2 = np.linspace(trajectorymat[nopoints + 1][1][0], trajectorymat[nopoints + 1][2][0])
lenx = len(x2)
x_arr2 = np.zeros(3*lenx)
y_arr2 = np.zeros(3*lenx)
z_arr2 = np.zeros(3*lenx)


[[0.         0.         0.        ]
 [0.         0.         1.        ]
 [0.75       1.29903811 2.59807621]
 [2.89777748 5.01909782 1.55291427]]
