In [1]:
import sys
sys.path.insert(0, '../')

from kineticspy.robobj import robot
from kineticspy import graphics, kin, trajectory, solidobj, measure, out

import math
import numpy as np

pi = math.pi

Declaring the robot object, in this case it is the arm

In [2]:
jointno = 3 # dont change
jointaxismat = [[0,0,1],[0,1,0],[0,1,0]] #dont change
lenmat = [[0,0,1],[0,0,2],[0,0,3]]
cmdmat = []

robot1 = robot.Robot(jointno,jointaxismat,lenmat,cmdmat)

robotinitialpos = robotfinalpos = graphics.position(robot1, robot1.coordmat)

Forward Kinematics

In [3]:
thetalist = [pi/2, pi/3, 2*pi/3]

coordmat = kin.fwd(robot1,thetalist)
robotfinalpos1 = graphics.position(robot1, coordmat)

data = robotfinalpos1 + robotinitialpos
m = graphics.plot(data)
#m.show()

Inverse Kinematics

In [4]:
pos = [-2.29, 3.98, 2]

thetalist = kin.inv(robot1, pos)
coordmat = kin.fwd(robot1,thetalist)
robotfinalpos2 = graphics.position(robot1, coordmat)

data = robotfinalpos2 + robotinitialpos
m = graphics.plot(data)
#m.show()

Straightline Trajectory Generation

In [5]:
pos1 = [-2.29, 3.98, 2]
pos2 = [-2.29, -3.98, 2]

trajectorymat = trajectory.linetrac(robot1, pos1, pos2)

trajectoryendeff = trajectory.trajectory_end(robot1, trajectorymat)
#uncomment and add below to see the trajectory of joints
#trajectoryjoints = trajectory.trajectory_joints(robot1, trajectorymat)

robo1 = graphics.position(robot1, trajectorymat[0])
robo2 = graphics.position(robot1, trajectorymat[len(trajectorymat) - 1])

data = trajectoryendeff + robo1 + robo2

print(robot1.cmdmat)
m = graphics.plot(data)
m.show()

[]


Natural Trajectory Generation

In [6]:
thetainit = [pi/2, pi/3, 2*pi/3]
thetafinal = [-pi/2, pi/3, 2*pi/3]
nopoint = 20

trajectorymat = trajectory.calctrac(robot1, thetainit, thetafinal, nopoint)

trajectoryendeff = trajectory.trajectory_end(robot1, trajectorymat)
#uncommetn and add below to see trajectory of joints
#trajectoryjoints = trajectory.trajectory_joints(robot1, trajectorymat)

robo1 = graphics.position(robot1, trajectorymat[0])
robo2 = graphics.position(robot1, trajectorymat[len(trajectorymat) - 1])

data = trajectoryendeff + robo1 + robo2

m = graphics.plot(data)
m.show()

You can also see the volume covered by adding the below command

vol = solidobj.volcov(robot1, trajectorymat)

Add obstacles: assume them as cuboid

In [7]:
l = 3
b = 3
h = 2
pos = [3,1,0]

Obstacle1 = solidobj.obstacle(l, b, h, pos)

l = 3
b = 3
h = 2
pos = [-3,-1,0]

Obstacle2 = solidobj.obstacle(l, b, h, pos)

In [8]:
viapoints = [[-2.29, 3.98, 2],[-2.29, -3.98, 2],[2.29, -3.98, 2],[2.29, 3.98, 2]]

trajectorymat = trajectory.viapts(robot1, viapoints)

trac_end = trajectory.trajectory_end(robot1, trajectorymat)
trac_joint = trajectory.trajectory_joints(robot1, trajectorymat)
vol = solidobj.volcovered(robot1, trajectorymat)
robo1 = graphics.position(robot1, trajectorymat[0])
robo2 = graphics.position(robot1, trajectorymat[len(trajectorymat) - 1])

new_data = Obstacle1 + Obstacle2 + trac_end + trac_joint + vol + robo1 + robo2

In [9]:
m = graphics.plot(new_data)
m.show()

In [10]:
orientation = [pi/2, pi/3, 2*pi/3]

mani_elip = measure.vel_mani_elip(robot1, orientation)
coordmat = kin.fwd(robot1,orientation)
robotpos = graphics.position(robot1, coordmat)

data = mani_elip + robotpos

m = graphics.plot(data)
m.show()

Eigen Values are:
[1.         4.69425418 0.63907916]

Manipulability Index: 	
2.7102289126004178


In [11]:
print(robot1.cmdmat)

[[ 2.0929138   0.9261183   0.712023  ]
 [ 2.2077182   0.49415928  1.33301494]
 [ 2.37371923  0.1730827   1.7270048 ]
 [ 2.61651004 -0.09258554  2.00019187]
 [ 2.95083065 -0.26274093  2.14920834]
 [ 3.33235466 -0.26274093  2.14920834]
 [ 3.66667527 -0.09258554  2.00019187]
 [ 3.90946607  0.1730827   1.7270048 ]
 [ 4.0754671   0.49415928  1.33301494]
 [ 4.19027151  0.9261183   0.712023  ]
 [ 4.19027151  0.9261183   0.712023  ]
 [ 4.29160321  0.76994943  0.94666031]
 [ 4.40300009  0.66481521  1.09852243]
 [ 4.52289776  0.59719791  1.19330476]
 [ 4.6485451   0.56372712  1.23933147]
 [-1.50695245  0.56372712  1.23933147]
 [-1.3813051   0.59719791  1.19330476]
 [-1.26140743  0.66481521  1.09852243]
 [-1.15001055  0.76994943  0.94666031]
 [-1.04867885  0.9261183   0.712023  ]
 [-1.04867885  0.9261183   0.712023  ]
 [-0.93387445  0.49415928  1.33301494]
 [-0.76787342  0.1730827   1.7270048 ]
 [-0.52508262 -0.09258554  2.00019187]
 [-0.190762   -0.26274093  2.14920834]
 [ 0.190762   -0.26274093

In [12]:
saving_location = "example.csv"
out.write(robot1, saving_location)